version: '3'
services:
  homeassistant:
    container_name: homeassistantv2
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    devices:
      - '/dev/ttyUSB0:/dev/ttyUSB0'
    restart: unless-stopped
    privileged: true
    network_mode: host
